.TH UPS-MONITOR 1 "09 February 2005" 
.SH NAME
UPS-MONITOR \- A graphical application to monitor the status of your UPS
.SH SYNOPSIS
.B ups-monitor

.SH DESCRIPTION
.PP
UPS monitor is a simple tool that displays UPS information in real time.
.PP
It can monitor a UPS attached to your computer, or a a network server
plugged into an UPS.
.PP
UPS monitor boasts these features:
.PP
\- Saves your session if UPS switches to battery power 
.TP
\- Warns you when power is critically low 
.TP
\- Lets you monitor networked UPSes 
.TP
\- Remembers configuration and restarts when you log on 
.TP
\- Extremely easy to use (because there's not much to actually use, methinks) 
.TP
\- Unobtrusive display as a tray icon 

.SH OPTIONS
.TP
ups-monitor supports standard GTK+ / Gnome / Bonobo options.
For a full list, call ups-monitor --help

.SH BUGS
None are known

.SH AUTHOR
This manual page was written by Arnaud Quette <arnaud.quette@mgeups.com>, for the Debian  project, and was modified by Manuel Amador <rudd-o@rudd-o.com>. It
may be used by others.

